language: android
jdk:
  - oraclejdk7

env:
  - TERM=dump

env:
  matrix:
    - ANDROID_TARGET=android-18 ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-20.0.0
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository

install:
  - true

script:
  - gradle test