language: android
jdk:
  - oraclejdk7

env:
  - TERM=dump

env:
  matrix:
    - ANDROID_TARGET=android-18 ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-20.0.0
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-598b93a6

install:
  - true

script:
  - gradle test